server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/dohands?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  config:
    import: optional:file:local.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

firebase:
  service-account-path: ${ACCOUNT_PATH}
  url: https://fcm.googleapis.com/v1/projects/${PROJECT_ID}/messages:send
  google-api: https://www.googleapis.com/auth/cloud-platform
  project-id: ${PROJECT_ID}