name: dohands server
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GCP credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > src/main/resources/credentials.json

      - name: Login to Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DI }}
          password: ${{ secrets.DP }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DI }}/dohands:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_PRIVATE_PATH }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker-compose down
            sudo docker pull ${{ secrets.DI }}/dohands:latest
            sudo docker-compose up -d
