name: dohands server
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ldh
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DI }}
          password: ${{ secrets.DP }}

      - name: bdi
        uses: docker/build-push-action@v5
        env:
          DU: ${{ secrets.DI }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.DU }}/dohands:latest
            ${{ env.DU }}/dohands:${{ github.sha }}
      - name: dts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_PRIVATE_PATH }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker-compose down
            sudo docker pull ${{ secrets.DI }}/dohands:latest
            sudo docker-compose up --build -d